### ISSUE TITLE
Docker container add pls 

### ISSUE THREAD

**Issue by MrSteelRat** [codeforreal1/compressO#11]
You need to add docker containers. If you are not competent in this, write. It would be interesting to work with this program from under a container

**Comment by niraj-khatiwada** [comment]
You cannot question over my competence and ask for a free favour. These kinds of derogatory comments are not welcomed in this repo.
There's no point in dockerizing the Tauri project besides the final release builds part for Linux. It would be better to use GitHub actions that Tauri team provides. There's no plan for this.
