### ISSUE TITLE
Not Really an An Issue

### ISSUE THREAD

**Issue by samihalawa** [codeforreal1/compressO#12]
Hello!

Sorry. I Just do not know where to leave the comment, thus I can only leave it here.
This is really awesome. Thank you so much. I love the hover effect when the file is dragged into the window.  And the decision of showing the result so visually (and well it is not showing off: man It compressed it by 94.77% that is crazy

![screenshot-compressO](https://github.com/user-attachments/assets/07914aff-9a41-4f40-a919-4455a277d522)

And  believe me, the credit is not completely on ffmpeg as I can  assure I have been trying some commands from this thread https://gist.github.com/lukehedger/277d136f68b028e22bed

And it even increased the size. I must get some additional background on all this compression thing, as I have never had to deal with it in my development projects and money clients seem to really enjoy having very very big video files in S3, (it makes them feel they are worth watching I guess) thus never needed it til today

Thank you so much again.

Sami (Madrid)

(please delete this message as it is not an issue and I jsut didn't manage to get it to anywhere else you could read it!)

**Comment by niraj-khatiwada** [comment]
Hi @samihalawa, thanks for the kind words. It really made my day🫶.
FFmpeg is really powerful specially when used precisely. I used the commands that outputs most optimum result over years of working with it. I'm really glad you found it useful. Thanks again!
