### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by iuvi7** [codeforreal1/compressO#13]
I would like to say - This is for sure on of the **TOP** programs i ever seen and been used! Hope one day it will came to all "Stores" in FOSS Distros

And feature\question request is - _**is it possible to make same GUI way of compression of audio files aswell?**_ 

Thank you very much 👍

**Comment by niraj-khatiwada** [comment]
@iuvi7 thanks for the kind words. It means a lot.
I started the project specifically for the video. There are no plans for the audio anytime soon. 
We might consider if there are plausible audience requests though. Thanks for the request.
