### ISSUE TITLE
Please generate a Portable version for Windows

### ISSUE THREAD

**Issue by gtang8** [codeforreal1/compressO#17]
Please generate a Portable version for Windows

**Comment by niraj-khatiwada** [comment]
Hey @gtang8 not sure what portable version means but I'm assuming Windows build? There's a Windows build already available. Please have a look at it [here](https://github.com/codeforreal1/compressO/releases/tag/v1.2.0).

**Comment by gtang8** [comment]
Actually the user has to install msi file in Windows, it couldn't be better for the user to unzip a ZIP or 7z file and run directly.

**Comment by niraj-khatiwada** [comment]
There are `msi` files for both Windows 64 and 32 version in the [release](https://github.com/codeforreal1/compressO/releases/tag/v1.2.0) page. The zip file is just zip of the source code not installers.
![image](https://github.com/user-attachments/assets/efbbc743-e723-44d3-acae-4f6a7f0d03e7)
