### ISSUE TITLE
Can't resize window vertically

### ISSUE THREAD

**Issue by slrgt** [codeforreal1/compressO#2]
Can't seem to resize the video vertically only horizontally (windows 11 64bit)

**Comment by niraj-khatiwada** [comment]
What do you mean by resize video? The app does not changes the dimension of the video. Can you give an example?

**Comment by slrgt** [comment]
Sorry i meant resize the window*.

https://github.com/codeforreal1/compressO/assets/114287507/da592199-5879-4e23-b239-e264a224743a

**Comment by niraj-khatiwada** [comment]
Aah, got it. So by default, the min dimension is 1080x992. But seems like 992 for height is too much. I'll try to adjust the frontend UI and reduce the min size.

**Comment by slrgt** [comment]
What's the benefit of having minimum dimensions? Won't this cause issues for people with older screens or people who use magnification accessibility features?

**Comment by niraj-khatiwada** [comment]
Hey, can you try on v1.10. It was just released. You can download it from [here](https://github.com/codeforreal1/compressO/releases/tag/v1.1.0)

**Comment by niraj-khatiwada** [comment]
> What's the benefit of having minimum dimensions? Won't this cause issues for people with older screens or people who use magnification accessibility features?

Just to avoid scroll and have consistent UI.

**Comment by slrgt** [comment]
> Hey, can you try on v1.10. It was just released. You can download it from [here](https://github.com/codeforreal1/compressO/releases/tag/v1.1.0)

It doesn't save the size after I close it so everytime i open it I have to resize it so it fits on my screen

**Comment by niraj-khatiwada** [comment]
> > Hey, can you try on v1.10. It was just released. You can download it from [here](https://github.com/codeforreal1/compressO/releases/tag/v1.1.0)
> 
> It doesn't save the size after I close it so everytime i open it I have to resize it so it fits on my screen

Hey this has been fixed in v1,2.0. Please try and install that build fro [here](https://github.com/codeforreal1/compressO/releases/tag/v1.2.0). Thanks

**Comment by slrgt** [comment]
Thank you that fixed it!
