### ISSUE TITLE
Feature Request: Drag and Drop videos

### ISSUE THREAD

**Issue by slrgt** [codeforreal1/compressO#3]
Would love to be able to drag and drop videos into compresso

Amazing app btw! Love that its also made using Tauri I haven't seen many applications or tutorials on Tauri yet

**Comment by niraj-khatiwada** [comment]
Drag and drop functionality has landed in v1.2.0. You can try it out from [here](https://github.com/codeforreal1/compressO/releases/tag/v1.2.0)
