### ISSUE TITLE
WTF

### ISSUE THREAD

**Issue by denegny** [codeforreal1/compressO#9]
WTF

![изображение](https://github.com/user-attachments/assets/ff122d13-68c1-44a4-af20-016cd477ef23)

**Comment by niraj-khatiwada** [comment]
It's not guaranteed that the final size will be less. It depends on different factors and the original video itself. When you try to compress the already optimized original video, the final size can be bigger. Also, try to use the quality slider to what you expect. This is just how FFmpeg works. In the future, we might allow to tweak the ffmpeg parameters passed to the command.
